# Generated by Django 5.2.17 on 2026-09-21 10:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import myapp.encryption
import myapp.models
import myapp.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_number",
                    myapp.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
                ),
                ("skills", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                (
                    "expected_salary",
                    myapp.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=myapp.storage_backends.PrivateResumeStorage(),
                        upload_to=myapp.models.resume_upload_path,
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "docx"])],
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="employer",
            name="company_website",
        ),
        migrations.AddField(
            model_name="application",
            name="ats_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume_snapshot",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=myapp.storage_backends.PrivateResumeStorage(),
                upload_to="resumes/snapshots/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "docx"])],
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(db_index=True, default="APPLIED", max_length=30),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employer",
            name="domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employer",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="employer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employer",
            name="size",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="experience_required",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("REMOTE", "Remote"),
                    ("CONTRACT", "Contract"),
                ],
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="Remote", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="applied_at",
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EMPLOYER", "Employer"),
                    ("CANDIDATE", "Candidate"),
                ],
                db_index=True,
                default="CANDIDATE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employer",
            name="company_name",
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_jobs",
                to="myapp.employer",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="employer",
            index=models.Index(
                fields=["is_deleted", "company_name"],
                name="myapp_emplo_is_dele_bc1361_idx",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="myapp.candidateprofile",
            ),
        ),
        migrations.RemoveField(
            model_name="application",
            name="cover_letter",
        ),
        migrations.DeleteModel(
            name="Candidate",
        ),
    ]
