# Generated by Django 5.2.17 on 2026-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_candidateprofile_remove_candidate_user_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="app_status_idx"),
        ),
    ]
